name: AWS S3 Operations

on:
  push:
    branches:
      - main

jobs:
  s3-operations:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@main

      # Step 2: Set up AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
            aws --version

      # Step 3: Configure AWS CLI 
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id AKIA6G75DYPHFLJ24OGQ
          aws configure set aws_secret_access_key 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
          aws configure set default.region ap-south-1

      # Step 4: List all S3 buckets
      - name: List all buckets
        run: |
          aws s3 ls

      # Step 5: Create a new bucket
      - name: Create a new bucket
        run: |
          BUCKET_NAME="github-action-s3-bucket-$(date +%s)"
          aws s3 mb s3://$BUCKET_NAME
          echo "Created bucket: $BUCKET_NAME"
    
     # Step 6: Upload a file to the bucket
      - name: Upload file to S3 bucket
        run: |
          echo "This is a test file" > test-file.txt
          BUCKET_NAME="github-action-s3-bucket-animesh"
          aws s3 cp test-file.txt s3://$BUCKET_NAME/test-file.txt

      
